# Generated by Django 3.2.4 on 2021-09-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_dep_file_ict_file_qb_file_rubrics_file_sylab_file_uni_exam_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dep_file',
            name='file_link',
            field=models.FileField(upload_to='media/department/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_link',
            field=models.FileField(upload_to='media/vision/'),
        ),
        migrations.AlterField(
            model_name='ict_file',
            name='file_link',
            field=models.FileField(upload_to='media/ict/'),
        ),
        migrations.AlterField(
            model_name='qb_file',
            name='file_link',
            field=models.FileField(upload_to='media/question_bank/'),
        ),
        migrations.AlterField(
            model_name='rubrics_file',
            name='file_link',
            field=models.FileField(upload_to='media/rubrics/'),
        ),
        migrations.AlterField(
            model_name='sylab_file',
            name='file_link',
            field=models.FileField(upload_to='media/syllabus/'),
        ),
        migrations.AlterField(
            model_name='uni_exam_file',
            name='file_link',
            field=models.FileField(upload_to='media/uni_exam/'),
        ),
    ]
