# Generated by Django 3.2.4 on 2021-10-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0003_auto_20210913_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dep_file',
            name='file_link',
            field=models.FileField(upload_to='department/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_link',
            field=models.FileField(upload_to='vision/'),
        ),
        migrations.AlterField(
            model_name='ict_file',
            name='file_link',
            field=models.FileField(upload_to='ict/'),
        ),
        migrations.AlterField(
            model_name='qb_file',
            name='file_link',
            field=models.FileField(upload_to='question_bank/'),
        ),
        migrations.AlterField(
            model_name='rubrics_file',
            name='file_link',
            field=models.FileField(upload_to='rubrics/'),
        ),
        migrations.AlterField(
            model_name='sylab_file',
            name='file_link',
            field=models.FileField(upload_to='syllabus/'),
        ),
        migrations.AlterField(
            model_name='uni_exam_file',
            name='file_link',
            field=models.FileField(upload_to='uni_exam/'),
        ),
    ]
